version: '3.8'

services:
  # Backend API service
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/rey-portfolio
      - JWT_SECRET=dev_secret_key_change_in_production
      - JWT_EXPIRES_IN=7d
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=dev-email@gmail.com
      - EMAIL_PASSWORD=dev-password
      - EMAIL_FROM=dev-email@gmail.com
      - EMAIL_TO=rey@example.com
      - UPLOAD_PATH=uploads/
      - RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    command: npm run dev

  # MongoDB service
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # MongoDB admin interface (optional)
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data: 